name: Android Build

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Update repositories
      run: sudo apt update 
    
    - name: Install packages
      run: sudo apt install cmake ninja-build openjdk-8-jdk wget unzip

    - name: Install Android SDK
      run: wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip && mkdir android-sdk-linux && unzip -qq android-sdk.zip -d android-sdk-linux && export ANDROID_HOME=./android-sdk-linux && echo y | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk-linux --update && (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk-linux --licenses

    - name: Build
      shell: bash
      run: cd $GITHUB_WORKSPACE/android && git submodule update --init && chmod +x gradlew && ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: SatDump-debug.apk
        path: $GITHUB_WORKSPACE/android/SatDump/build/outputs/apk/debug/SatDump-debug.apk