name: Windows Build

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Clone pre-setup VCPKG
        run: git clone https://github.com/Aang23/vcpkg.git --depth 1

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Download SDRPlay API
        shell: powershell
        run: Invoke-WebRequest -Uri "https://files.altillimity.com/SDRPlay.zip" -OutFile ${{runner.workspace}}/sdrplay.zip

      - name: Install SDRPlay API
        shell: powershell
        run: 7z x ${{runner.workspace}}/sdrplay.zip -O"${{runner.workspace}}"

      - name: Copy SDRPlay API Files
        shell: powershell
        run: cp -r "${{runner.workspace}}/SDRPlay/API/inc/*" $Env:GITHUB_WORKSPACE/vcpkg/installed/x64-windows/include/; cp "${{runner.workspace}}/SDRPlay/API/x64/sdrplay_api.dll" $Env:GITHUB_WORKSPACE/vcpkg/installed/x64-windows/bin/sdrplay_api.dll; cp "${{runner.workspace}}/SDRPlay/API/x64/sdrplay_api.lib" $Env:GITHUB_WORKSPACE/vcpkg/installed/x64-windows/lib/sdrplay_api.lib;

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake -G "Visual Studio 16 2019" -DBUILD_MSVC=ON -DBUILD_LIVE=ON -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake "$Env:GITHUB_WORKSPACE"

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --config $BUILD_TYPE

      - name: Copy DLLs
        working-directory: ${{runner.workspace}}/build
        shell: powershell
        run: cp $Env:GITHUB_WORKSPACE/vcpkg/installed/x64-windows/bin/*.dll Release

      - name: Copy Resources
        working-directory: ${{runner.workspace}}/build
        shell: powershell
        run: cp -r $Env:GITHUB_WORKSPACE/resources Release

      - name: Copy Pipelines
        working-directory: ${{runner.workspace}}/build
        shell: powershell
        run: cp -r $Env:GITHUB_WORKSPACE/pipelines ${{runner.workspace}}/build/Release; cp $Env:GITHUB_WORKSPACE/Roboto-Medium.ttf ${{runner.workspace}}/build/Release

      - name: Copy Fonts
        working-directory: ${{runner.workspace}}/build
        shell: powershell
        run: cp $Env:GITHUB_WORKSPACE/Roboto-Medium.ttf Release

      - name: Upload ZIP
        uses: actions/upload-artifact@v2
        with:
          name: SatDump-Windows_x64_MSVC
          path: ${{runner.workspace}}/build/Release/*
